apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
data:
  application.properties: |
    spring.datasource.url=jdbc:mysql://mysql:3306/akouma_stock
    spring.datasource.username=root
    spring.datasource.password=